# 使用的 actions:
# https://github.com/marketplace/actions/automatic-releases
name: Main

on:
  push:
    branches: [ main ]
  # schedule:
  #   - cron: '0 8 * * 0'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it 13
      - uses: actions/checkout@v2
      - name: download
        run: |
          sudo apt-get update
          #sudo apt-get install ffmpeg curl rar python3 aria2 -y
          #pip3 install you-get
          #you-get --itag=136 -O ./result/1917541 -k --debug 'https://www.youtube.com/watch?v=-7njmMDeBa9c'

          sudo apt-get install ffmpeg
          wget https://github.com/yt-dlp/yt-dlp/releases/latest/download/yt-dlp -O /usr/local/bin/yt-dlp
          chmod a+rx /usr/local/bin/yt-dlp
          yt-dlp -f 136+140 --merge-output-format mp4 -o ./result/2278733.mp4 'https://www.youtube.com/watch?v=TtqWpYj8oXo'
          
          #sudo apt-get install ffmpeg curl -y
          #wget https://go.dev/dl/go1.22.4.linux-amd64.tar.gz -O go.tar.gz
          #sudo tar -xzf go.tar.gz -C /usr/local
          #echo export PATH=$HOME/go/bin:/usr/local/go/bin:$PATH >> ~/.profile
          #source ~/.profile
          #go version
          ##curl -L https://git.io/vQhTU | bash -s -- --version 1.22
          #go install github.com/iawia002/lux@latest
          #lux -f 136 -O ./result/2295101 'https://www.youtube.com/watch?v=9E1aDs7WVI4'

      - name: Release
        uses: marvinpinto/action-automatic-releases@latest
        with:
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          automatic_release_tag: ${{ github.run_id }}
          prerelease: false
          title: ${{ github.run_id }}
          files: |
            result/*
        
