# 使用的 actions:
# https://github.com/marketplace/actions/automatic-releases
name: Main

on:
  push:
    branches: [ main ]
  # schedule:
  #   - cron: '0 8 * * 0'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it 13
      - uses: actions/checkout@v2
      - name: download
        run: |
          sudo apt-get update
          #sudo apt-get install ffmpeg curl rar python3 aria2 -y
          #pip3 install you-get
          #you-get --itag=136 -O ./result/1917541 -k --debug 'https://www.youtube.com/watch?v=-7njmMDeBa9c'

          sudo apt-get install ffmpeg curl rar go  -y
          go install github.com/iawia002/lux@latest
          lux -f 136 -O ./result/2295101 'https://www.youtube.com/watch?v=9E1aDs7WVI4'

      - name: Release
        uses: marvinpinto/action-automatic-releases@latest
        with:
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          automatic_release_tag: ${{ github.run_id }}
          prerelease: false
          title: ${{ github.run_id }}
          files: |
            result/*
        
